name: Develop Workflow

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint
        run: echo "Running lint step"

      - name: Test
        run: echo "Running test step"

      - name: Build
        env:
          KUBE_CONFIG: ${{ secrets.DEV_KUBECONFIG }}
        run: |
          echo "The value of DEV_KUBECONFIG secret is $KUBE_CONFIG"

      - name: Deploy
        run: echo "Running deploy step"
