name: 1. Lint Workflow

on:
  push:
    branches:
      - feature/**
      - fix/**
      - refactor/**
      - test/**

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Lint
        run: echo "Running lint step"

  test:
    name: Test
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: echo "Running test step"
