name: Release Workflow

on:
  workflow_dispatch:
    # inputs:
    #   branch:
    #     description: 'Select a release branch'
    #     required: true
    #     default: 'release/'

jobs:
  promote:
    name: Promote to Prod
    runs-on: ubuntu-latest

    steps:

      - name: Get Latest Commit
        id: get_commit
        run: |
          selected_branch="${{ github.branch }}"
          if [[ ! "$selected_branch" =~ ^release/.*$ ]]; then
            echo "Error: Invalid branch name. Please select a branch starting with 'release/'."
            exit 1
          fi
  
          echo "${{github.sha}}"
