name: Prod Workflow

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select a release branch'
        required: true
        default: 'release/'

jobs:
  get_latest_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Latest Commit
        id: get_commit
        run: |
          selected_branch="${{ github.event.inputs.branch }}"
          latest_commit=$(curl -s "https://api.github.com/repos/${{ github.repository }}/commits/${selected_branch}" | jq -r '.sha')

          echo "::set-output name=latest_commit::$latest_commit"

      - name: Print Latest Commit
        run: echo "The latest commit hash for the selected branch is ${{ steps.get_commit.outputs.latest_commit }}"
